apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-dotnet-dev
spec:
  destination:
    namespace: simple-dotnet-dev
    server: https://kubernetes.default.svc
  project: simple-dotnet
  source:
    path: app/overlays/dev
    repoURL: https://dev.azure.com/redhat-demo/simple-dotnet-service-deploy/_git/simple-dotnet-service-deploy
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true


