apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-dotnet-prod
spec:
  project: simple-dotnet
  source:
    path: app/overlays/prod
    repoURL: https://redhat-demo@dev.azure.com/redhat-demo/simple-dotnet-service-deploy/_git/simple-dotnet-service-deploy
    targetRevision: main
  destination:
    namespace: simple-dotnet-prod
    server: https://kubernetes.default.svc
  syncPolicy: {}